name: teenytinytwodee
description: A rapid prototyping framework for 2D games
version: 1.0.0
repository: https://github.com/alexayers/daaaart.git

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10
  lints: ^4.0.0
  test: ^1.25.5
