name: test_bed
description: A example project for testing changes to teenytinytwodee
version: 1.0.0
publish_to: 'none'
repository: https://github.com/alexayers/daaaart.git

environment:
  sdk: ^3.2.4

dependencies:
  teenytinytwodee:
    path: ../teenytinytwodee
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
