name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - test_bed
          - fishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          cache: true

      - name: Get dependencies
        run: dart pub get
        working-directory: "packages/${{ matrix.package }}"    

      - name: Activate WebDev
        run: dart pub global activate webdev

      - name: Build project
        run: webdev build
        working-directory: "packages/${{ matrix.package }}"

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: 'daaaart'
          service_account: 'daaaart-github-uploads@daaart.iam.gserviceaccount.com'

      - name: 'Upload Build to GCP'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: '/home/runner/work/daaaart/build/${{ matrix.package }}'
          destination: 'daaaart/${{ matrix.package }}'         


