name: PR Check

on:
    pull_request:
        branches:
        - main
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"
          cache: true
      - run: dart pub get
      - run: dart format --set-exit-if-changed ./
      - run: dart analyze
      - run: |
          if [ -d "test" ]; then
            dart test --coverage=coverage
            echo "has_coverage=true" >> $GITHUB_ENV
          else
            echo "has_coverage=false" >> $GITHUB_ENV
          fi
      - name: Install coverage tools
        if: env.has_coverage == 'true'
        run: dart pub global activate coverage
      - name: format coverage
        if: env.has_coverage == 'true'
        run: $HOME/.pub-cache/bin/format_coverage --lcov --in=coverage --out=coverage.lcov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.3.1
        with:
          files: coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
       
            